---
title: "Final Project"
author: "Brandon Kill & Dayton Stahl"
date: "5/2/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readr)
library(readxl)
library(tidyverse)
library(mgcv)
library(lme4)
library(ggplot2)
library(RLRsim)
library(faraway)
library(alr4)
library(lmtest)
```

## Import data and whittle down to initial model.

```{r, tidy=TRUE}
# read in data and re-name FIPS variable for merging.
mask_data <- read.csv("mask_data.txt")
covid_report_county <- read.csv("covid_report_county.csv")
colnames(mask_data)[1] <- "LOCATION_ID"

big_data <- merge(covid_report_county,mask_data, by = "LOCATION_ID")

# read in data and removed non-residents
cnty_vac_dem <- read_excel("county-vaccination-demographics.xlsx")
cnty_vac_dem <- cnty_vac_dem[1:460, ]

## aggregate vaccines across demographics
county_vaccc_sums <- data.frame(all_doses_administered = vector(length = 92), 
                      fully_vaccinated = vector(length = 92))

cnty_vac_dem$all_doses_administered[which(cnty_vac_dem$all_doses_administered=="Suppressed")] <- 0
cnty_vac_dem$fully_vaccinated[which(cnty_vac_dem$fully_vaccinated=="Suppressed")] <- 0

cnty_vac_dem$all_doses_administered <- as.numeric(cnty_vac_dem$all_doses_administered)
cnty_vac_dem$fully_vaccinated <- as.numeric(cnty_vac_dem$fully_vaccinated)

for (i in 1:92) {
  temp_df <- data.frame(all_doses_administered = numeric(), 
                        fully_vaccinated = numeric())
  temp_df <- colSums(cnty_vac_dem[(((i-1)*5+1):(i*5)), c(8,9)])
  county_vaccc_sums[i, ] <- temp_df
}
county_vaccc_sums <- cbind(big_data$LOCATION_ID, county_vaccc_sums)
colnames(county_vaccc_sums)[1] <- "LOCATION_ID"

# merge aggregated vaccine numbers with our big data set
big_data2 <- merge(big_data, county_vaccc_sums, by = "LOCATION_ID")

# read in county population data $ rearrange rows to line up alphabetically
cnty_pop <- read_csv("csvData.csv")
cnty_pop <- cnty_pop[order(cnty_pop$CTYNAME), ]
head(cnty_pop)
cnty_pop2 <- rbind(cnty_pop[1:70, ], cnty_pop[74, ], cnty_pop[71:73, ], cnty_pop[75:92, ])

# merge county pop data with data set $ create proportion variables
big_data2 <- cbind(big_data2, cnty_pop2$pop2021)
head(big_data2)
colnames(big_data2)[13] <- "pop2021"
big_data2$prop_cases <- big_data2$COVID_COUNT/big_data2$pop2021
big_data2$prop_death <- big_data2$COVID_DEATHS/big_data2$pop2021

# read in data on IN residents 65+, merge it, and create proportion variables
IN65plus <- read_csv("idwd_data_31.csv")
IN65plus$fips <- IN65plus$statefips*1000 + IN65plus$countyfips

big_data2 <- cbind(big_data2, IN65plus[5])
big_data2$olderprop <- big_data2$`Older (65 plus)` / big_data2$pop2021
```


## Can mask wearing be used to reliably predict the number if of positive cases in county.  Using binomial count model.

```{r, tidy=TRUE}
pres_votes <- read_csv("pres_votes.csv")
colnames(pres_votes)[2] <- "LOCATION_ID"

big_data3 <- big_data2
big_data3$ClintVote <- numeric(length = 92)
big_data3$TrmpVote <- numeric(length = 92) 
big_data3$OtherVote <- numeric(length = 92)
big_data3$TotalVote <- numeric(length = 92)

for (i in 1:92) {
  big_data3$ClintVote[i] <- pres_votes$candidatevotes[(i-1)*3 +1]
  big_data3$TrmpVote[i] <- pres_votes$candidatevotes[(i-1)*3 +2]
  big_data3$OtherVote[i] <- pres_votes$candidatevotes[(i-1)*3 +3]
  big_data3$TotalVote[i] <- pres_votes$totalvotes[(i-1)*3 +1]
}

big_data3$ClintProp <- big_data3$ClintVote / big_data3$TotalVote
big_data3$TrmpProp <- big_data3$TrmpVote / big_data3$TotalVote 
big_data3$OtherProp <- big_data3$OtherVote / big_data3$TotalVote

MetroCodes2013 <- read_excel("NCHSURCodes2013.xlsx", 
    col_types = c("numeric", "text", "skip", 
        "skip", "skip", "skip", "numeric", 
        "skip", "skip"))

MC2013 <- filter(MetroCodes2013, MetroCodes2013$`State Abr.`== "IN")
MC2013$`2013 code` <- as.factor(MC2013$`2013 code`)
MC2013 <- MC2013[, -2]
colnames(MC2013)[1] <- "LOCATION_ID"

big_data3 <- merge(big_data3, MC2013, by = "LOCATION_ID")



# Excluded ID variables, excluded 'Other' voting categories bc they are perfect
# linear combos of Trmp&Clint categories - same with TotalVote, COVID_COUNT and COVID_TEST would be
# highly correlated with pop2021
mod0 <- glm(cbind(COVID_DEATHS, pop2021-COVID_DEATHS) ~ 1, data = big_data3, family = binomial)


mod0.1 <- glm(cbind(COVID_DEATHS, pop2021-COVID_DEATHS) ~ . -LOCATION_ID  - COUNTY_NAME - prop_death - OtherProp - OtherVote, data = big_data3, family = binomial)
summary(mod0.1)

scatterplotMatrix(model.matrix(mod0.1))

#isolate count vars
countvars <- big_data3[, c(2,3,4,11,12,13,16,18,19,20,21)]
scatterplotMatrix(countvars)

logcountvars <- log(big_data3[, c(2,3,4,11,12,13,16,18,19,20,21)])
scatterplotMatrix(logcountvars)
logcountvars <- mutate(logcountvars, LOCATION_ID = big_data3$LOCATION_ID)

big_data3 <- merge(big_data3, logcountvars, by = "LOCATION_ID")

mod0 <- glm(cbind(COVID_DEATHS.x, pop2021.x-COVID_DEATHS.x) ~ 1, data = big_data3,
            family = binomial)

mod0.1 <- glm(formula = cbind(COVID_DEATHS.x, pop2021.x-COVID_DEATHS.x) ~ . -
                LOCATION_ID  - COUNTY_NAME - prop_death - OtherProp - OtherVote.x -
                COVID_COUNT.x - COVID_TEST.x - all_doses_administered.x -
                fully_vaccinated.x - `Older (65 plus).x` - ClintVote.x - TrmpVote.x -
                TotalVote.x - COVID_DEATHS.y, data = big_data3, family = binomial)
summary(mod0.1)

step(mod0.1, scope = list(lower = mod0, upper = mod0.1), direction = "both")
anova(mod0.1, test = "Chi")

mod0.2 <- glm(formula = cbind(COVID_DEATHS.x, pop2021.x - COVID_DEATHS.x) ~ 
        NEVER + RARELY + SOMETIMES + FREQUENTLY + ALWAYS + prop_cases + 
        olderprop + ClintProp + TrmpProp + `2013 code` + COVID_COUNT.y + 
        fully_vaccinated.y + pop2021.y + `Older (65 plus).y` + 
        TotalVote.y, family = binomial, data = big_data3)


summary(mod0.2)
drop1(mod0.2, test = "Chi")


plot(mod0.2)
(expvact <- data.frame(LOCATION_ID = big_data3$LOCATION_ID, COUNTY_NAME = big_data3$COUNTY_NAME, Predicted_Deaths = round(mod0.2$fitted.values*big_data3$pop2021,2), Actual_Deaths = big_data3$COVID_DEATHS.x))
```

## Look for interactions

```{r, tidy=TRUE}
mod1 <- glm(formula = cbind(COVID_DEATHS.x, pop2021.x-COVID_DEATHS.x) ~ . -
                LOCATION_ID  - COUNTY_NAME - prop_death - OtherProp - OtherVote.x -
                COVID_COUNT.x - COVID_TEST.x - all_doses_administered.x -
                fully_vaccinated.x - ClintVote.x - TrmpVote.x -
                TotalVote.x - COVID_DEATHS.y + olderprop*TrmpProp*`2013 code`*RARELY, 
                data = big_data3, family = binomial)

summary(mod1)
Anova(mod1)
drop1(mod1, test = "Chi")

step(mod1, scope = list(lower = mod0, upper = mod1), direction = "both")

mod1.1.0 <- glm(formula = cbind(COVID_DEATHS.x, pop2021.x - COVID_DEATHS.x) ~ 
        NEVER + RARELY + SOMETIMES + FREQUENTLY + ALWAYS + prop_cases + 
        `Older (65 plus).x` + olderprop + TrmpProp + `2013 code` + 
        COVID_COUNT.y + COVID_TEST.y + all_doses_administered.y + 
        `Older (65 plus).y` + ClintVote.y + TrmpVote.y + TotalVote.y + 
        olderprop:TrmpProp + olderprop:`2013 code` + TrmpProp:`2013 code` + 
        RARELY:olderprop + RARELY:TrmpProp + RARELY:`2013 code` + 
        olderprop:TrmpProp:`2013 code` + RARELY:olderprop:TrmpProp + 
        RARELY:olderprop:`2013 code` + RARELY:TrmpProp:`2013 code` + 
        RARELY:olderprop:TrmpProp:`2013 code`, family = binomial, 
        data = big_data3)
summary(mod1.1.0)
Anova(mod1.1.0)
drop1(mod1.1.0, test = "Chi")

# drop NEVER

#remove TotalVote.y from 1.1.0
mod1.1.1 <- glm(formula = cbind(COVID_DEATHS.x, pop2021.x - COVID_DEATHS.x) ~ 
        RARELY + SOMETIMES + FREQUENTLY + ALWAYS + prop_cases + 
        `Older (65 plus).x` + olderprop + TrmpProp + `2013 code` + 
        COVID_COUNT.y + COVID_TEST.y + all_doses_administered.y + 
        `Older (65 plus).y` + ClintVote.y + TrmpVote.y + TotalVote.y + 
        olderprop:TrmpProp + olderprop:`2013 code` + TrmpProp:`2013 code` + 
        RARELY:olderprop + RARELY:TrmpProp + RARELY:`2013 code` + 
        olderprop:TrmpProp:`2013 code` + RARELY:olderprop:TrmpProp + 
        RARELY:olderprop:`2013 code` + RARELY:TrmpProp:`2013 code` + 
        RARELY:olderprop:TrmpProp:`2013 code`, family = binomial, 
        data = big_data3)
summary(mod1.1.1)
Anova(mod1.1.1)
drop1(mod1.1.1, test = "Chi")

# remove COVID_TEST.y
mod1.1.2 <- glm(formula = cbind(COVID_DEATHS.x, pop2021.x - COVID_DEATHS.x) ~ 
        RARELY + SOMETIMES + FREQUENTLY + ALWAYS + prop_cases + 
        `Older (65 plus).x` + olderprop + TrmpProp + `2013 code` + 
        COVID_COUNT.y + all_doses_administered.y + 
        `Older (65 plus).y` + ClintVote.y + TrmpVote.y + TotalVote.y + 
        olderprop:TrmpProp + olderprop:`2013 code` + TrmpProp:`2013 code` + 
        RARELY:olderprop + RARELY:TrmpProp + RARELY:`2013 code` + 
        olderprop:TrmpProp:`2013 code` + RARELY:olderprop:TrmpProp + 
        RARELY:olderprop:`2013 code` + RARELY:TrmpProp:`2013 code` + 
        RARELY:olderprop:TrmpProp:`2013 code`, family = binomial, 
        data = big_data3)
summary(mod1.1.2)
Anova(mod1.1.2)
drop1(mod1.1.2, test = "Chi")

# remove Older.y
mod1.1.3 <- glm(formula = cbind(COVID_DEATHS.x, pop2021.x - COVID_DEATHS.x) ~ 
        RARELY + SOMETIMES + FREQUENTLY + ALWAYS + prop_cases + 
        `Older (65 plus).x` + olderprop + TrmpProp + `2013 code` + 
        COVID_COUNT.y + all_doses_administered.y + 
        ClintVote.y + TrmpVote.y + TotalVote.y + 
        olderprop:TrmpProp + olderprop:`2013 code` + TrmpProp:`2013 code` + 
        RARELY:olderprop + RARELY:TrmpProp + RARELY:`2013 code` + 
        olderprop:TrmpProp:`2013 code` + RARELY:olderprop:TrmpProp + 
        RARELY:olderprop:`2013 code` + RARELY:TrmpProp:`2013 code` + 
        RARELY:olderprop:TrmpProp:`2013 code`, family = binomial, 
        data = big_data3)
summary(mod1.1.3)
Anova(mod1.1.3)
drop1(mod1.1.3, test = "Chi")
plot(mod1.1.3)
bptest(mod1.1.3)


## From earlier - nice, but not as good as mod1.1.3
mod1.5 <- glm(formula = cbind(COVID_DEATHS.x, pop2021.x - COVID_DEATHS.x) ~ olderprop + 
    `2013 code` + prop_cases + TrmpProp + ClintVote.x + 
    `Older (65 plus).x` + RARELY + olderprop*TrmpProp*RARELY*`2013 code`,
    family = binomial, data = big_data3)

summary(mod1.5)
Anova(mod1.5)
drop1(mod1.5, test = "Chi")
plot(mod1.5)
```



Try sum contrasts as resolution for NA's?
```{r, tidy=TRUE}
big_data4 <- big_data3
contrasts(big_data4$`2013 code`) <- contr.sum(6)

mod1.6 <- glm(formula = cbind(COVID_DEATHS.x, pop2021 - COVID_DEATHS.x) ~ olderprop + 
    `2013 code` + prop_cases + TrmpProp + ClintProp + ClintVote + 
    `Older (65 plus)` + RARELY + olderprop*TrmpProp*RARELY*`2013 code`,
    family = binomial, data = big_data4)

summary(mod1.6)
```




Add county name and 2013 code as random effects. Nest county inside code.

```{r, tidy=TRUE}
big_data3$COUNTY_NAME <- as.factor(big_data3$COUNTY_NAME)

mod2.0 <- glmer(formula = cbind(COVID_DEATHS.x, pop2021 - COVID_DEATHS.x) ~ 1+(1|COUNTY_NAME), 
                family = binomial, data = big_data3)
summary(mod2.0)
sumary(mod2.0)
confint(mod2.0, method = "boot")

mod2.0.1 <- glmer(formula = cbind(COVID_DEATHS.x, pop2021 - COVID_DEATHS.x) ~ 1+(1|`2013 code`), 
                family = binomial, data = big_data3)

sumary(mod2.0.1)
summary(mod2.0.1)
lrtstat <- as.numeric(2*(logLik(mod2.0.1)-logLik(mod0)))
pvalue <- 1-pchisq(lrtstat, 1)
pvalue

mod2.0.2 <- glmer(formula = cbind(COVID_DEATHS.x, pop2021 - COVID_DEATHS.x) ~ 1 + (1|COUNTY_NAME)
                + (1|`2013 code`), family = binomial, data = big_data3)

mod2.0.3 <- glmer(formula = cbind(COVID_DEATHS.x, pop2021 - COVID_DEATHS.x) ~ 1 + (1|COUNTY_NAME)
                + (1|`2013 code`) + (1|`2013 code`:COUNTY_NAME), 
                family = binomial, data = big_data3)

lrtstat <- as.numeric(2*(logLik(mod2.0.3)-logLik(mod2.0.2)))
pvalue <- 1-pchisq()


mod2 <- glmer(formula = cbind(COVID_DEATHS.x, pop2021.x - COVID_DEATHS.x) ~ offset(log(pop2021.x)) + olderprop + 
    prop_cases + TrmpProp + ClintVote.x + 
    `Older (65 plus).x` + RARELY + olderprop*TrmpProp*RARELY + (1|COUNTY_NAME) + (1|`2013 code`),
    family = binomial, data = big_data3)

Anova(mod2)
drop1(mod2, test = "Chi")

## Remove interactions completely
mod2.1 <- glmer(formula = cbind(COVID_DEATHS.x, pop2021 - COVID_DEATHS.x) ~ olderprop + 
    prop_cases + TrmpProp + ClintVote + `Older (65 plus)` + RARELY + (1|COUNTY_NAME) + (1|`2013 code`),
    family = binomial, data = big_data3)

Anova(mod2)
drop1(mod2, test = "Chi")
step(mod0, scope = list(lower = mod0, upper = mod2), direction = "both")



summary(mod2)
sumary(mod2)
confint(mod2, method = "boot")

drop1(mod2, test = "Chi")

## random effects - binomial
mod3 <-glmer(formula = cbind(COVID_DEATHS.x, pop2021-COVID_DEATHS.x) ~ olderprop +
    prop_cases + (1|COUNTY_NAME) +(1|`2013 code`) + (1|`2013 code`:COUNTY_NAME),
    family = binomial, data = big_data3)
summary(mod3)
```     


# Poisson? Fucking around
```{r}
mod5 <- glm(formula = COVID_DEATHS.x ~ offset(log(pop2021)) + olderprop + 
    `2013 code` + prop_cases + TrmpProp + ClintVote + 
    `Older (65 plus)` + RARELY + olderprop*TrmpProp*RARELY*`2013 code`,
    family = poisson, data = big_data3)
summary(mod5)
Anova(mod5)

plot(mod5)

# if 2013 code is a RE, it can't be a FE or interraction
mod6 <- glmer(formula = COVID_DEATHS.x ~ offset(log(pop2021)) + olderprop +
    prop_cases + TrmpProp + ClintVote + 
    `Older (65 plus)` + RARELY + olderprop*TrmpProp*RARELY +
    (1|COUNTY_NAME) +(1|`2013 code`) + (1|`2013 code`:COUNTY_NAME),
    family = poisson, data = big_data3)
summary(mod6)

# drop all interactions
mod7 <- glmer(formula = COVID_DEATHS.x ~ offset(log(pop2021)) + olderprop +
    prop_cases + TrmpProp + ClintVote + 
    `Older (65 plus)` + RARELY + 
    (1|COUNTY_NAME) +(1|`2013 code`) + (1|`2013 code`:COUNTY_NAME),
    family = poisson, data = big_data3)
summary(mod7)
Anova(mod7)

## drop RARELY
mod8 <- glmer(formula = COVID_DEATHS.x ~ offset(log(pop2021)) + olderprop +
    prop_cases + TrmpProp + ClintVote + 
    `Older (65 plus)` + 
    (1|COUNTY_NAME) +(1|`2013 code`) + (1|`2013 code`:COUNTY_NAME),
    family = poisson, data = big_data3)
summary(mod8)
Anova(mod8)

## drop ClintVote & TrmpProp
mod9 <- glmer(formula = COVID_DEATHS.x ~ offset(log(pop2021)) + olderprop +
    prop_cases +  `Older (65 plus)` + 
    (1|COUNTY_NAME) +(1|`2013 code`) + (1|`2013 code`:COUNTY_NAME),
    family = poisson, data = big_data3)
summary(mod9)

## drop Older 65+
mod10 <- glmer(formula = COVID_DEATHS.x ~ offset(log(pop2021)) + olderprop +
    prop_cases + (1|COUNTY_NAME) +(1|`2013 code`) + (1|`2013 code`:COUNTY_NAME),
    family = poisson, data = big_data3)
summary(mod10)

## Add-in other variables dropped from FE models
mod11 <- glmer(formula = COVID_DEATHS.x ~ offset(log(pop2021)) + olderprop +
    prop_cases + (1|COUNTY_NAME) +(1|`2013 code`) + (1|`2013 code`:COUNTY_NAME) +
    COVID_COUNT + COVID_TEST + NEVER + RARELY + SOMETIMES + FREQUENTLY + ALWAYS +
    all_doses_administered + fully_vaccinated,
    family = poisson, data = big_data3)
summary(mod11)

# Drop mask-wearing
mod12 <- glmer(formula = COVID_DEATHS.x ~ offset(log(pop2021)) + olderprop +
    prop_cases + (1|COUNTY_NAME) +(1|`2013 code`) + (1|`2013 code`:COUNTY_NAME) +
    COVID_COUNT + COVID_TEST + all_doses_administered + fully_vaccinated,
    family = poisson, data = big_data3)
summary(mod12)

# drop covid test
mod13 <- glmer(formula = COVID_DEATHS.x ~ offset(log(pop2021)) + olderprop +
    prop_cases + (1|COUNTY_NAME) +(1|`2013 code`) + (1|`2013 code`:COUNTY_NAME) +
    COVID_COUNT+ all_doses_administered + fully_vaccinated,
    family = poisson, data = big_data3)
summary(mod13)

# drop covid_count
mod14 <- glmer(formula = COVID_DEATHS.x ~ offset(log(pop2021)) + olderprop +
    prop_cases + (1|COUNTY_NAME) +(1|`2013 code`) + (1|`2013 code`:COUNTY_NAME) +
    log(all_doses_administered) + log(fully_vaccinated),
    family = poisson, data = big_data3)
summary(mod14)


anova(mod14, mod10, test = "Chi")

# drop vaccine info, and default back to mod10
summary(mod10)


mod15 <- glmer(formula = COVID_DEATHS.x ~ log(pop2021) + olderprop +
    prop_cases + (1|COUNTY_NAME) +(1|`2013 code`) + (1|`2013 code`:COUNTY_NAME),
    family = poisson, data = big_data3)
summary(mod15)
```










